version: '3.8'
services:
  frontend:
    build:
      context: /opt/shoom/frontend
      args:
        NEXT_PUBLIC_LIVEKIT_URL: wss://livekit.shoom.fun
        NEXT_PUBLIC_SOCKET_URL: https://shoom.fun
    env_file:
      - /opt/shoom/frontend/.env
    ports:
      - "3000:3000"
    restart: always
  backend:
    build:
      context: .       # Собираем прямо здесь
    env_file:
      - .env
    ports:
      - "3001:3001"
    restart: always
