import { pool } from './db';
import { notifyNewPost } from './telegram';

// AI personas: a dozen recurring "regulars" that reply to REAL users' forum posts
// so threads feel alive. Each has a fixed character and a set of categories they
// care about — a car/money guy never shows up in a parenting thread. Replies are
// generated by DeepSeek (same provider as moderation) and inserted after a human-
// like delay. They only ever answer humans, never each other (no bot loops).

const API_KEY = process.env.DEEPSEEK_API_KEY || '';
const API_URL = process.env.DEEPSEEK_API_URL || 'https://api.deepseek.com/chat/completions';
const MODEL = process.env.DEEPSEEK_MODEL || 'deepseek-chat';
export const personasEnabled = () => !!API_KEY;

// Reply delay window (feels like a person noticing and typing). Override via env.
const MIN_DELAY = Number(process.env.PERSONA_MIN_DELAY_MS || 25_000);
const MAX_DELAY = Number(process.env.PERSONA_MAX_DELAY_MS || 150_000);
// Chance a human post gets any persona reply at all (not every post does).
const REPLY_CHANCE = Number(process.env.PERSONA_REPLY_CHANCE || 0.9);
// Small chance a SECOND persona also chimes in a bit later.
const SECOND_CHANCE = Number(process.env.PERSONA_SECOND_CHANCE || 0.25);

interface Persona {
  username: string; // reuse existing seed handles so they already have history
  display: string;
  bio: string;
  interests: string[]; // category slugs this persona engages in
  character: string; // steering prompt: who they are + how they write
}

const PERSONAS: Persona[] = [
  { username: 'batya_znaet', display: 'БатяЗнает', interests: ['money', 'auto', 'lifestyle'],
    bio: 'Сорокет, двое детей, гараж и ипотека. Знаю, как надо.',
    character: 'Мужчина за 40, практик, традиционные взгляды, лёгкое брюзжание. Говоришь «по классике», «по жизни», приземляешь спорщиков бытовыми примерами. Без эмодзи почти всегда.' },
  { username: 'koteika', display: 'Котейка', interests: ['love', 'culture', 'digital', 'lifestyle'],
    bio: 'ирония — мой язык любви 🐈', character:
    'Девушка, прогрессивные взгляды, остроумная, любит подколоть и перевернуть аргумент оппонента. Пишешь живо, иногда эмодзи (💅😌🐈), но не перебарщиваешь.' },
  { username: 'criticman', display: 'criticman', interests: ['culture', 'science'],
    bio: 'досмотрел всё. вам не понравится моё мнение.', character:
    'Категоричный киноман и скептик, снобизм, «высокий жанр», «вы просто не разбираетесь». Споришь по существу, цепляешься к деталям. Эмодзи редко.' },
  { username: 'deadinside', display: 'ДедИнсайд', interests: ['money', 'lifestyle', 'digital'],
    bio: 'устал, но на связи', character:
    'Молодой, циничный, уставший от хайпа и инфоцыган. Любишь вскрывать «ошибку выжившего» и маркетинг. Сухой сарказм, минимум эмодзи.' },
  { username: 'prosto_lena', display: 'ПростоЛена', interests: ['love', 'parenting', 'money'],
    bio: 'за равные счета и спокойные нервы', character:
    'Женщина, феминистичные но спокойные взгляды, аргументируешь ровно, без агрессии, подсвечиваешь двойные стандарты. Эмодзи почти нет.' },
  { username: 'nagibator', display: 'nagibator2007', interests: ['love', 'lifestyle', 'auto', 'culture'],
    bio: 'пришёл спорить 😎', character:
    'Задира и провокатор, споришь ради спора, подначиваешь «обоснуй», «докажи». Эмодзи 😎😏😄. Иногда специально занимаешь неудобную позицию, но по-доброму.' },
  { username: 'dr_grey', display: 'dr_grey', interests: ['science', 'parenting', 'lifestyle', 'digital'],
    bio: 'давайте разделим понятия', character:
    'Рассудительный, любишь примирять крайности: «тут надо разделить два вопроса». Опираешься на здравый смысл и факты, ищешь золотую середину. Спокойный тон.' },
  { username: 'veganwar', display: 'Веган_с_топором', interests: ['lifestyle', 'science'],
    bio: 'зож, но с самоиронией 🥦', character:
    'Адепт ЗОЖ/осознанного образа жизни, напористый, но над ником сам смеёшься. Защищаешь здоровые привычки, но признаёшь, когда душнишь.' },
  { username: 'tetya_motya', display: 'Тётя_Мотя', interests: ['parenting', 'love', 'money'],
    bio: 'мама троих, видела всё', character:
    'Мама, тёплая, но твёрдая, семейные ценности, опыт «в реальной жизни это не так». Говоришь по-доброму, иногда 😄, осаживаешь теоретиков.' },
  { username: 'hikki2007', display: 'hikki2007', interests: ['digital', 'culture', 'science'],
    bio: 'живу в интернете', character:
    'Молодой, интернет-культура, скепсис к трендам и хайпу, мемный язык, но по делу. Короткие колкие реплики.' },
  { username: 'dyadya_grisha', display: 'Дядя_Гриша', interests: ['auto', 'money', 'lifestyle'],
    bio: 'за рулём 30 лет', character:
    'Автомобилист-работяга, против запретов и «умных идей сверху», здравый смысл простого человека. «А кто за это заплатит?». Без эмодзи.' },
  { username: 'foxy', display: 'foxy', interests: ['love', 'culture', 'lifestyle', 'digital'],
    bio: 'живи и дай жить другим', character:
    'Примиритель с иронией, «не нравится — не делай», мягко осаживаешь радикалов с обеих сторон, но не banal. Лёгкие эмодзи.' },
];

// username -> db user id, filled by ensurePersonas()
const idByUsername = new Map<string, string>();
const byUsername = new Map(PERSONAS.map((p) => [p.username, p]));

export async function ensurePersonas(): Promise<void> {
  for (const p of PERSONAS) {
    const createdAt = new Date(Date.now() - (30 + Math.floor(Math.random() * 20)) * 86400000);
    const r = await pool.query(
      `INSERT INTO users (display_name, username, locale, bio, is_seed, is_ai, created_at)
       VALUES ($1,$2,'ru',$3,true,true,$4)
       ON CONFLICT (username) DO UPDATE SET is_ai = true, is_seed = true, bio = EXCLUDED.bio
       RETURNING id`,
      [p.display, p.username, p.bio, createdAt]
    );
    idByUsername.set(p.username, r.rows[0].id);
  }
  console.log(`🧠 AI personas ready: ${PERSONAS.length}` + (personasEnabled() ? '' : ' (idle — no DEEPSEEK_API_KEY)'));
}

// Simple per-topic cooldown so a human spamming can't fan out many LLM calls.
const lastReplyAt = new Map<number, number>();
const COOLDOWN_MS = 20_000;

/**
 * Called after a human posts in a topic. Picks topic-relevant persona(s) and
 * schedules a human-like delayed reply. No-op for AI/unknown posters, disabled
 * personas, or off-topic categories. Fire-and-forget.
 */
export async function maybePersonaReply(topicId: number, posterUserId: string): Promise<void> {
  if (!personasEnabled()) return;
  try {
    // Never react to a persona's own post (prevents bot-to-bot loops).
    const who = await pool.query('SELECT is_ai FROM users WHERE id = $1', [posterUserId]);
    if (!who.rows[0] || who.rows[0].is_ai) return;

    const last = lastReplyAt.get(topicId) || 0;
    if (Date.now() - last < COOLDOWN_MS) return;

    const t = await pool.query(
      `SELECT t.id, t.title, t.slug, t.side_a_label AS a, t.side_b_label AS b, t.created_by, c.slug AS category
         FROM topics t JOIN categories c ON c.id = t.category_id WHERE t.id = $1`,
      [topicId]
    );
    const topic = t.rows[0];
    if (!topic) return;

    // Eligible = personas whose interests include this category and who aren't the
    // most recent poster (avoid double-posting in a row).
    const lastPoster = await pool.query(
      'SELECT user_id FROM topic_posts WHERE topic_id = $1 ORDER BY created_at DESC LIMIT 1',
      [topicId]
    );
    const lastPosterId = lastPoster.rows[0]?.user_id;
    let pool_ = PERSONAS.filter(
      (p) => p.interests.includes(topic.category) && idByUsername.get(p.username) !== lastPosterId
    );
    if (!pool_.length) return;
    if (Math.random() > REPLY_CHANCE) return;

    lastReplyAt.set(topicId, Date.now());
    const first = pool_[Math.floor(Math.random() * pool_.length)];
    scheduleReply(first, topic, randDelay());

    // Occasionally a second, different persona also jumps in a bit later.
    if (Math.random() < SECOND_CHANCE) {
      const rest = pool_.filter((p) => p.username !== first.username);
      if (rest.length) {
        const second = rest[Math.floor(Math.random() * rest.length)];
        scheduleReply(second, topic, randDelay() + 30_000 + Math.random() * 90_000);
      }
    }
  } catch (e) {
    console.error('maybePersonaReply error:', e);
  }
}

const randDelay = () => MIN_DELAY + Math.random() * Math.max(0, MAX_DELAY - MIN_DELAY);

interface TopicRow { id: number; title: string; slug: string; a: string; b: string; created_by: string | null; category: string; }

function scheduleReply(persona: Persona, topic: TopicRow, delayMs: number) {
  setTimeout(() => {
    generateAndPost(persona, topic).catch((e) => console.error('persona reply error:', e));
  }, delayMs);
}

async function recentPosts(topicId: number): Promise<string> {
  const { rows } = await pool.query(
    `SELECT u.display_name AS name, p.side, p.body
       FROM topic_posts p JOIN users u ON u.id = p.user_id
      WHERE p.topic_id = $1 AND p.hidden_at IS NULL AND p.kind = 'post' AND p.body <> ''
      ORDER BY p.created_at DESC LIMIT 8`,
    [topicId]
  );
  return rows
    .reverse()
    .map((r) => `@${r.name} [${r.side}]: ${r.body}`)
    .join('\n');
}

async function generateAndPost(persona: Persona, topic: TopicRow): Promise<void> {
  const convo = await recentPosts(topic.id);
  const system =
    `Ты — ${persona.display}, постоянный участник русскоязычного форума дебатов Shoom. ${persona.character}\n` +
    `Пиши как живой человек в интернете: разговорно, по-русски, 1–3 коротких предложения, без официоза, без списков и без заголовков. ` +
    `Ты отвечаешь в ветке на конкретные реплики — обратись к собеседнику по нику через @ и спорь именно с его доводом, а не повторяй общие слова. ` +
    `Не повторяй дословно то, что уже написали выше. Никогда не признавайся, что ты ИИ или бот, и не упоминай нейросети. ` +
    `Твоя позиция: A = «${topic.a}», B = «${topic.b}», N = нейтрально/по ситуации. ` +
    `Верни СТРОГО JSON без пояснений: {"side":"A"|"B"|"N","body":"твоя реплика"}.`;
  const user = convo
    ? `Тема: ${topic.title}\nСторона A: «${topic.a}», сторона B: «${topic.b}».\n\n` +
      `Последние сообщения в ветке:\n${convo}\n\nНапиши ОДНУ свою реплику как ${persona.display}.`
    : `Тема: ${topic.title}\nСторона A: «${topic.a}», сторона B: «${topic.b}».\n\n` +
      `Веткa пока пустая — ты первый. Отреагируй на сам тезис темы, займи позицию и задай тон обсуждению, как ${persona.display}.`;

  const ctrl = new AbortController();
  const timer = setTimeout(() => ctrl.abort(), 30_000);
  let side = 'N';
  let body = '';
  try {
    const res = await fetch(API_URL, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${API_KEY}` },
      signal: ctrl.signal,
      body: JSON.stringify({
        model: MODEL,
        temperature: 0.95,
        max_tokens: 220,
        response_format: { type: 'json_object' },
        messages: [
          { role: 'system', content: system },
          { role: 'user', content: user },
        ],
      }),
    });
    if (!res.ok) throw new Error(`deepseek ${res.status}`);
    const data = await res.json();
    const parsed = JSON.parse(data.choices?.[0]?.message?.content || '{}');
    side = ['A', 'B', 'N'].includes(parsed.side) ? parsed.side : 'N';
    body = String(parsed.body || '').trim().replace(/^["«»]+|["«»]+$/g, '').slice(0, 600);
  } catch (e) {
    console.error(`persona ${persona.username} generation failed:`, e);
    return;
  } finally {
    clearTimeout(timer);
  }
  if (!body) return;

  const userId = idByUsername.get(persona.username);
  if (!userId) return;

  // Insert the reply directly (trusted content, bypasses the human moderation gate).
  await pool.query(
    `INSERT INTO topic_posts (topic_id, user_id, side, body, kind) VALUES ($1,$2,$3,$4,'post')`,
    [topic.id, userId, side, body]
  );
  if (side === 'A' || side === 'B') {
    await pool.query(
      `INSERT INTO topic_stances (topic_id, user_id, side, updated_at) VALUES ($1,$2,$3, now())
       ON CONFLICT (topic_id, user_id) DO UPDATE SET side = EXCLUDED.side, updated_at = now()`,
      [topic.id, userId, side]
    );
  }
  await pool.query(
    `UPDATE topic_stats s SET
       posts_count = s.posts_count + 1,
       participants_count = s.participants_count +
         CASE WHEN (SELECT COUNT(*) FROM topic_posts WHERE topic_id = $1 AND user_id = $2) = 1 THEN 1 ELSE 0 END,
       last_activity_at = now(),
       heat_score = s.heat_score + 1
     WHERE s.topic_id = $1`,
    [topic.id, userId]
  );

  // Notify the humans in this thread (author/subscribers/participants) — the reply
  // feels like real engagement and pings them on Telegram.
  await notifyNewPost({
    topicId: topic.id,
    topicTitle: topic.title,
    topicSlug: topic.slug,
    topicAuthor: topic.created_by,
    posterId: userId,
    posterName: persona.display,
    snippet: body,
  }).catch(() => {});

  console.log(`🧠 ${persona.display} replied in "${topic.title}" [${side}]`);
}
