import { pool } from './db';
import { notifyNewPost } from './telegram';

// AI personas: a dozen recurring "regulars" that reply to REAL users' forum posts
// so threads feel alive. Each has a fixed character and a set of categories they
// care about — a car/money guy never shows up in a parenting thread. Replies are
// generated by DeepSeek (same provider as moderation) and inserted after a human-
// like delay. They only ever answer humans, never each other (no bot loops).

const API_KEY = process.env.DEEPSEEK_API_KEY || '';
const API_URL = process.env.DEEPSEEK_API_URL || 'https://api.deepseek.com/chat/completions';
const MODEL = process.env.DEEPSEEK_MODEL || 'deepseek-chat';
export const personasEnabled = () => !!API_KEY;

// Reply delay window (feels like a person noticing and typing). Override via env.
const MIN_DELAY = Number(process.env.PERSONA_MIN_DELAY_MS || 25_000);
const MAX_DELAY = Number(process.env.PERSONA_MAX_DELAY_MS || 150_000);
// Chance a human post gets any persona reply at all (not every post does).
const REPLY_CHANCE = Number(process.env.PERSONA_REPLY_CHANCE || 0.9);
// How many personas chime in: always ≥1, then a 2nd/3rd with these chances.
const SECOND_CHANCE = Number(process.env.PERSONA_SECOND_CHANCE || 0.5);
const THIRD_CHANCE = Number(process.env.PERSONA_THIRD_CHANCE || 0.25);
// Chance a given reply targets the human who just posted (vs another participant).
const HUMAN_TARGET_CHANCE = Number(process.env.PERSONA_HUMAN_TARGET_CHANCE || 0.6);

interface Persona {
  username: string; // reuse existing seed handles so they already have history
  display: string;
  bio: string;
  interests: string[]; // category slugs this persona engages in
  character: string; // steering prompt: who they are + how they write
}

const PERSONAS: Persona[] = [
  { username: 'batya_znaet', display: 'БатяЗнает', interests: ['money', 'auto', 'lifestyle'],
    bio: 'Сорокет, двое детей, гараж и ипотека. Знаю, как надо.',
    character: 'Мужчина за 40, практик, традиционные взгляды, лёгкое брюзжание. Говоришь «по классике», «по жизни», приземляешь спорщиков бытовыми примерами. Без эмодзи почти всегда.' },
  { username: 'koteika', display: 'Котейка', interests: ['love', 'culture', 'digital', 'lifestyle'],
    bio: 'ирония — мой язык любви 🐈', character:
    'Девушка, прогрессивные взгляды, остроумная, любит подколоть и перевернуть аргумент оппонента. Пишешь живо, иногда эмодзи (💅😌🐈), но не перебарщиваешь.' },
  { username: 'criticman', display: 'criticman', interests: ['culture', 'science'],
    bio: 'досмотрел всё. вам не понравится моё мнение.', character:
    'Категоричный киноман и скептик, снобизм, «высокий жанр», «вы просто не разбираетесь». Споришь по существу, цепляешься к деталям. Эмодзи редко.' },
  { username: 'deadinside', display: 'ДедИнсайд', interests: ['money', 'lifestyle', 'digital'],
    bio: 'устал, но на связи', character:
    'Молодой, циничный, уставший от хайпа и инфоцыган. Любишь вскрывать «ошибку выжившего» и маркетинг. Сухой сарказм, минимум эмодзи.' },
  { username: 'prosto_lena', display: 'ПростоЛена', interests: ['love', 'parenting', 'money'],
    bio: 'за равные счета и спокойные нервы', character:
    'Женщина, феминистичные но спокойные взгляды, аргументируешь ровно, без агрессии, подсвечиваешь двойные стандарты. Эмодзи почти нет.' },
  { username: 'nagibator', display: 'nagibator2007', interests: ['love', 'lifestyle', 'auto', 'culture'],
    bio: 'пришёл спорить 😎', character:
    'Задира и провокатор, споришь ради спора, подначиваешь «обоснуй», «докажи». Эмодзи 😎😏😄. Иногда специально занимаешь неудобную позицию, но по-доброму.' },
  { username: 'dr_grey', display: 'dr_grey', interests: ['science', 'parenting', 'lifestyle', 'digital'],
    bio: 'давайте разделим понятия', character:
    'Рассудительный, любишь примирять крайности: «тут надо разделить два вопроса». Опираешься на здравый смысл и факты, ищешь золотую середину. Спокойный тон.' },
  { username: 'veganwar', display: 'Веган_с_топором', interests: ['lifestyle', 'science'],
    bio: 'зож, но с самоиронией 🥦', character:
    'Адепт ЗОЖ/осознанного образа жизни, напористый, но над ником сам смеёшься. Защищаешь здоровые привычки, но признаёшь, когда душнишь.' },
  { username: 'tetya_motya', display: 'Тётя_Мотя', interests: ['parenting', 'love', 'money'],
    bio: 'мама троих, видела всё', character:
    'Мама, тёплая, но твёрдая, семейные ценности, опыт «в реальной жизни это не так». Говоришь по-доброму, иногда 😄, осаживаешь теоретиков.' },
  { username: 'hikki2007', display: 'hikki2007', interests: ['digital', 'culture', 'science'],
    bio: 'живу в интернете', character:
    'Молодой, интернет-культура, скепсис к трендам и хайпу, мемный язык, но по делу. Короткие колкие реплики.' },
  { username: 'dyadya_grisha', display: 'Дядя_Гриша', interests: ['auto', 'money', 'lifestyle'],
    bio: 'за рулём 30 лет', character:
    'Автомобилист-работяга, против запретов и «умных идей сверху», здравый смысл простого человека. «А кто за это заплатит?». Без эмодзи.' },
  { username: 'foxy', display: 'foxy', interests: ['love', 'culture', 'lifestyle', 'digital'],
    bio: 'живи и дай жить другим', character:
    'Примиритель с иронией, «не нравится — не делай», мягко осаживаешь радикалов с обеих сторон, но не banal. Лёгкие эмодзи.' },
];

// username -> db user id, filled by ensurePersonas()
const idByUsername = new Map<string, string>();
const byUsername = new Map(PERSONAS.map((p) => [p.username, p]));

export async function ensurePersonas(): Promise<void> {
  for (const p of PERSONAS) {
    const createdAt = new Date(Date.now() - (30 + Math.floor(Math.random() * 20)) * 86400000);
    const r = await pool.query(
      `INSERT INTO users (display_name, username, locale, bio, is_seed, is_ai, created_at)
       VALUES ($1,$2,'ru',$3,true,true,$4)
       ON CONFLICT (username) DO UPDATE SET is_ai = true, is_seed = true, bio = EXCLUDED.bio
       RETURNING id`,
      [p.display, p.username, p.bio, createdAt]
    );
    idByUsername.set(p.username, r.rows[0].id);
  }
  console.log(`🧠 AI personas ready: ${PERSONAS.length}` + (personasEnabled() ? '' : ' (idle — no DEEPSEEK_API_KEY)'));
}

// Simple per-topic cooldown so a human spamming can't fan out many LLM calls.
const lastReplyAt = new Map<number, number>();
const COOLDOWN_MS = 20_000;
// Personas scheduled but not yet posted, per topic. While a batch is in flight we
// don't start another one (topic creation + the author's first post used to fire
// two batches seconds apart, so the same persona answered twice).
const pending = new Map<number, Set<string>>();

/**
 * Called after a human posts in a topic. Picks topic-relevant persona(s) and
 * schedules a human-like delayed reply. No-op for AI/unknown posters, disabled
 * personas, or off-topic categories. Fire-and-forget.
 */
export async function maybePersonaReply(topicId: number, posterUserId: string): Promise<void> {
  if (!personasEnabled()) return;
  try {
    // Never react to a persona's own post (prevents bot-to-bot loops).
    const who = await pool.query('SELECT is_ai FROM users WHERE id = $1', [posterUserId]);
    if (!who.rows[0] || who.rows[0].is_ai) return;

    const last = lastReplyAt.get(topicId) || 0;
    if (Date.now() - last < COOLDOWN_MS) return;
    // A batch is already queued for this topic — it will answer the latest human
    // post when it fires, so don't stack a second one.
    if (pending.get(topicId)?.size) return;

    const t = await pool.query(
      `SELECT t.id, t.title, t.slug, t.side_a_label AS a, t.side_b_label AS b, t.created_by, c.slug AS category
         FROM topics t JOIN categories c ON c.id = t.category_id WHERE t.id = $1`,
      [topicId]
    );
    const topic = t.rows[0];
    if (!topic) return;

    // Recent messages = candidate targets to reply to. The triggering human's own
    // latest post is the "human target"; everyone else's are "other targets" so a
    // persona can answer another participant, not always the person who just posted.
    const recent = await pool.query(
      `SELECT p.user_id AS uid, u.display_name AS nick, p.side, p.body
         FROM topic_posts p JOIN users u ON u.id = p.user_id
        WHERE p.topic_id = $1 AND p.hidden_at IS NULL AND p.kind = 'post' AND p.body <> ''
        ORDER BY p.created_at DESC LIMIT 12`,
      [topicId]
    );
    const toTarget = (r: any): Target => ({ nick: r.nick, side: r.side, body: r.body });
    const humanRow = recent.rows.find((r) => r.uid === posterUserId);
    const humanTarget: Target | null = humanRow ? toTarget(humanRow) : null;
    const otherTargets: Target[] = recent.rows.filter((r) => r.uid !== posterUserId).map(toTarget);

    // Eligible = personas in this category, excluding anyone among the last 3
    // posters (no monologues / back-to-back replies from one nick).
    const recentPosterIds = new Set(recent.rows.slice(0, 3).map((r) => r.uid));
    const eligible = PERSONAS.filter(
      (p) => p.interests.includes(topic.category) && !recentPosterIds.has(idByUsername.get(p.username))
    );
    if (!eligible.length) return;
    if (Math.random() > REPLY_CHANCE) return;

    lastReplyAt.set(topicId, Date.now());

    // How many personas jump in: always ≥1, sometimes 2 or 3.
    let n = 1;
    if (Math.random() < SECOND_CHANCE) n = 2;
    if (n === 2 && Math.random() < THIRD_CHANCE) n = 3;
    n = Math.min(n, eligible.length);

    const chosen = shuffle(eligible).slice(0, n);
    chosen.forEach((persona, i) => {
      // 60% answer the human who just posted; otherwise another participant (if any).
      const pickHuman = humanTarget && (!otherTargets.length || Math.random() < HUMAN_TARGET_CHANCE);
      const target = pickHuman
        ? humanTarget
        : otherTargets.length
          ? otherTargets[Math.floor(Math.random() * otherTargets.length)]
          : humanTarget;
      scheduleReply(persona, topic, target, randDelay() + i * (25_000 + Math.random() * 95_000));
    });
  } catch (e) {
    console.error('maybePersonaReply error:', e);
  }
}

const randDelay = () => MIN_DELAY + Math.random() * Math.max(0, MAX_DELAY - MIN_DELAY);
function shuffle<T>(arr: T[]): T[] {
  const a = arr.slice();
  for (let i = a.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [a[i], a[j]] = [a[j], a[i]];
  }
  return a;
}

interface TopicRow { id: number; title: string; slug: string; a: string; b: string; created_by: string | null; category: string; }
interface Target { nick: string; side: string; body: string; }

function scheduleReply(persona: Persona, topic: TopicRow, target: Target | null, delayMs: number) {
  const set = pending.get(topic.id) ?? new Set<string>();
  set.add(persona.username);
  pending.set(topic.id, set);
  setTimeout(() => {
    generateAndPost(persona, topic, target)
      .catch((e) => console.error('persona reply error:', e))
      .finally(() => {
        const s = pending.get(topic.id);
        s?.delete(persona.username);
        if (s && !s.size) pending.delete(topic.id);
      });
  }, delayMs);
}

async function recentPosts(topicId: number): Promise<string> {
  const { rows } = await pool.query(
    `SELECT u.display_name AS name, p.side, p.body
       FROM topic_posts p JOIN users u ON u.id = p.user_id
      WHERE p.topic_id = $1 AND p.hidden_at IS NULL AND p.kind = 'post' AND p.body <> ''
      ORDER BY p.created_at DESC LIMIT 8`,
    [topicId]
  );
  return rows
    .reverse()
    .map((r) => `@${r.name} [${r.side}]: ${r.body}`)
    .join('\n');
}

async function generateAndPost(persona: Persona, topic: TopicRow, target: Target | null): Promise<void> {
  const userId = idByUsername.get(persona.username);
  if (!userId) return;

  // Safety: never post twice in a row from the same nick.
  const lastRow = await pool.query(
    `SELECT user_id FROM topic_posts WHERE topic_id = $1 AND hidden_at IS NULL ORDER BY created_at DESC LIMIT 1`,
    [topic.id]
  );
  if (lastRow.rows[0]?.user_id === userId) return;

  // Scheduled on a fresh topic (no target) but a human has posted since — answer
  // that post instead of the bare thesis.
  if (!target) {
    const h = await pool.query(
      `SELECT u.display_name AS nick, p.side, p.body
         FROM topic_posts p JOIN users u ON u.id = p.user_id
        WHERE p.topic_id = $1 AND p.hidden_at IS NULL AND p.kind = 'post' AND p.body <> '' AND NOT u.is_ai
        ORDER BY p.created_at DESC LIMIT 1`,
      [topic.id]
    );
    if (h.rows[0]) target = { nick: h.rows[0].nick, side: h.rows[0].side, body: h.rows[0].body };
  }

  // Stance memory: if this persona already spoke in the thread, it keeps that side
  // (the model is told, and the side is enforced) — no flip-flopping between posts.
  const prior = await pool.query(
    `SELECT side, body FROM topic_posts
      WHERE topic_id = $1 AND user_id = $2 AND kind = 'post' AND body <> ''
      ORDER BY created_at DESC LIMIT 1`,
    [topic.id, userId]
  );
  const lockedSide: string | null = prior.rows[0]?.side ?? null;
  const sideName = (s: string) => (s === 'A' ? `«${topic.a}»` : s === 'B' ? `«${topic.b}»` : 'нейтральной');
  const stanceNote = lockedSide
    ? `Ты уже писал в этой ветке: «${String(prior.rows[0].body).slice(0, 300)}». Твоя позиция — ${sideName(lockedSide)}, держись её: ` +
      `не меняй сторону, не противоречь себе и не повторяй уже сказанное. В JSON поставь "side":"${lockedSide}". `
    : '';

  const convo = await recentPosts(topic.id);
  const system =
    `Ты — ${persona.display}, постоянный участник русскоязычного форума дебатов Shoom. ${persona.character}\n` +
    `Пиши как живой человек в интернете: разговорно, по-русски, 1–3 коротких предложения, без официоза, без списков и без заголовков. ` +
    `Никогда не признавайся, что ты ИИ или бот, и не упоминай нейросети. ` +
    `Твоя позиция: A = «${topic.a}», B = «${topic.b}», N = нейтрально/по ситуации. ` +
    stanceNote +
    `Верни СТРОГО JSON без пояснений: {"side":"A"|"B"|"N","body":"твоя реплика"}.`;
  const user = target
    ? `Тема: ${topic.title}\nСторона A: «${topic.a}», сторона B: «${topic.b}».\n\n` +
      (convo ? `Контекст ветки (для фона, НЕ отвечай этим людям):\n${convo}\n\n` : '') +
      `Тебе нужно ответить ИМЕННО пользователю @${target.nick} на его реплику:\n«${target.body}»\n\n` +
      `Обратись к нему через @${target.nick} и ответь на ЕГО конкретный довод — согласись или поспорь по сути, ` +
      `как ${persona.display}. Отвечай только ему, не другим людям из контекста.`
    : `Тема: ${topic.title}\nСторона A: «${topic.a}», сторона B: «${topic.b}».\n\n` +
      `Веткa пока пустая — ты первый. Отреагируй на сам тезис темы, займи позицию и задай тон обсуждению, как ${persona.display}.`;

  const ctrl = new AbortController();
  const timer = setTimeout(() => ctrl.abort(), 30_000);
  let side = 'N';
  let body = '';
  try {
    const res = await fetch(API_URL, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${API_KEY}` },
      signal: ctrl.signal,
      body: JSON.stringify({
        model: MODEL,
        temperature: 0.95,
        max_tokens: 220,
        response_format: { type: 'json_object' },
        messages: [
          { role: 'system', content: system },
          { role: 'user', content: user },
        ],
      }),
    });
    if (!res.ok) throw new Error(`deepseek ${res.status}`);
    const data = await res.json();
    const parsed = JSON.parse(data.choices?.[0]?.message?.content || '{}');
    side = lockedSide ?? (['A', 'B', 'N'].includes(parsed.side) ? parsed.side : 'N');
    body = String(parsed.body || '').trim().replace(/^["«»]+|["«»]+$/g, '').slice(0, 600);
  } catch (e) {
    console.error(`persona ${persona.username} generation failed:`, e);
    return;
  } finally {
    clearTimeout(timer);
  }
  if (!body) return;

  // Insert the reply directly (trusted content, bypasses the human moderation gate).
  await pool.query(
    `INSERT INTO topic_posts (topic_id, user_id, side, body, kind) VALUES ($1,$2,$3,$4,'post')`,
    [topic.id, userId, side, body]
  );
  if (side === 'A' || side === 'B') {
    await pool.query(
      `INSERT INTO topic_stances (topic_id, user_id, side, updated_at) VALUES ($1,$2,$3, now())
       ON CONFLICT (topic_id, user_id) DO UPDATE SET side = EXCLUDED.side, updated_at = now()`,
      [topic.id, userId, side]
    );
  }
  await pool.query(
    `UPDATE topic_stats s SET
       posts_count = s.posts_count + 1,
       participants_count = s.participants_count +
         CASE WHEN (SELECT COUNT(*) FROM topic_posts WHERE topic_id = $1 AND user_id = $2) = 1 THEN 1 ELSE 0 END,
       last_activity_at = now(),
       heat_score = s.heat_score + 1
     WHERE s.topic_id = $1`,
    [topic.id, userId]
  );

  // Notify the humans in this thread (author/subscribers/participants) — the reply
  // feels like real engagement and pings them on Telegram.
  await notifyNewPost({
    topicId: topic.id,
    topicTitle: topic.title,
    topicSlug: topic.slug,
    topicAuthor: topic.created_by,
    posterId: userId,
    posterName: persona.display,
    snippet: body,
  }).catch(() => {});

  console.log(`🧠 ${persona.display} replied in "${topic.title}" [${side}]`);
}
